"""Synthetic-demo mode — runs realistic 4-turn fake conversations per specialist
via PAVO directly, without AgentPhone.

Use cases:
  1. Rehearsal: run the full demo flow without needing AgentPhone API keys.
  2. Backup video: record a clean 90-second demo for the worst-case scenario
     where AgentPhone fails on stage.
  3. Pre-stage testing: verify the dashboard + PAVO + cost ticker without
     waiting for real outbound calls to connect.

Architecture:
  - Each specialist runs a 4-turn conversation in-process (no AgentPhone, no webhook)
  - Both sides of the conversation are generated by PAVO via separate role_hints
  - Real PAVO routing decisions fire (the routing layer is genuinely exercised)
  - Real cost is accumulated (gemma-local turns ~0.005c each; gemini-flash 18%; opus 2%)
  - All WebSocket events flow normally to the dashboard

The synthetic counterparty turns use a different role_hint ("counterparty-{category}")
so PAVO can still classify them appropriately. For the demo, this is real PAVO
routing — only the AgentPhone leg is skipped.
"""
from __future__ import annotations

import asyncio
import logging
import time
from typing import Any

from .pavo_client import pavo_chat
from .personas import Persona, by_id
from .state import state, SpecialistCallContext
from .ws import ws_broker


log = logging.getLogger(__name__)


# Per-category prompt scaffolding to make synthetic counterparty replies feel real.
COUNTERPARTY_OPENERS = {
    "utility-electric-gas": "PG&E customer service, this is Diana, how can I help you?",
    "utility-internet-sf": "Thanks for calling Comcast retention, this is Marcus.",
    "insurance-auto": "Geico, this is Patricia, may I have your policy number?",
    "postal": "USPS COA form loaded.",
    "utility-internet-austin": "Spectrum new service, this is Ryan, how can I help?",
    "mover": "Atlas Moving and Storage, this is Tony. How can I help?",
}


COUNTERPARTY_TURN_TEMPLATES = {
    "utility-electric-gas": [
        "What's the account holder's name and service address?",
        "Got it. We can schedule disconnect for {move_date}. Will there be anyone at the property for the meter read?",
        "Confirmed. Disconnect scheduled for {move_date}, confirmation 8472341. Final bill will arrive within 4 weeks.",
    ],
    "utility-internet-sf": [
        "I see the account. Why are we losing you? Anything we can do?",
        "I understand. Effective date {move_date}. There's an early-termination fee but we'll waive it for out-of-area moves. Final bill is in 2 cycles.",
        "Cancellation confirmation 41872, final bill {move_date_plus_45}. Please return your modem within 14 days.",
    ],
    "insurance-auto": [
        "Got the policy. Old address San Francisco, new address Austin Texas. New rate is $142 a month, down from your $186. Effective {move_date}.",
        "Confirmation reference TX-948-2A. New policy card mails out tomorrow.",
        "Anything else?",
    ],
    "postal": [
        "Filling: old SF address, new Austin address, move date {move_date}, family.",
        "Step 2: identity verification charge $1.10 against the card on file. Confirming.",
        "Submission complete. USPS confirmation 4081-3293-7762-4419. COA effective {move_date}.",
    ],
    "utility-internet-austin": [
        "Welcome. Service address please?",
        "Coverage confirmed. Spectrum Internet Ultra 500 megabit, install on {move_date}, technician between 8 AM and noon. Install fee $50 — waiving as new account.",
        "Work order WO2847391024. We'll text you when the tech is 30 minutes out.",
    ],
    "mover": [
        "2-bedroom San Francisco to Austin, May 31 — let me work up a quote. About 5,000 pounds, no piano, no safe?",
        "OK. Out the door $1,840 includes packing, fuel, basic insurance. Deposit $500, balance due on delivery. Truck confirmed for May 31.",
        "I can hold the slot for 24 hours. After that I can't promise.",
    ],
}

AGENT_OPENERS = {
    "utility-electric-gas": "Hi, calling on behalf of {user_name} to schedule a service disconnect at {origin_address} on {move_date}.",
    "utility-internet-sf": "Hi, calling to cancel Comcast service at {origin_address}, effective {move_date}.",
    "insurance-auto": "Hello, calling to update the policy mailing and garage address. Old: {origin_address}. New: {destination_address}. Effective {move_date}.",
    "postal": "Initiating COA: old {origin_address}, new {destination_address}, move date {move_date}.",
    "utility-internet-austin": "Hi, scheduling new internet install at {destination_address}, target install {move_date}.",
    "mover": "Calling for an out-the-door quote: 2BR move from {origin_address} to {destination_address}, target {move_date}.",
}


def _format(template: str, spec: dict[str, Any]) -> str:
    """Naive format helper that swallows missing keys."""
    try:
        return template.format(**spec, move_date_plus_45="early July")
    except KeyError as e:
        log.warning("synthetic template missing key %s; substituting placeholder", e)
        return template.format_map({**spec, "move_date_plus_45": "early July", str(e).strip("'"): "<unknown>"})


async def run_synthetic_specialist(persona: Persona, event_id: str, spec: dict[str, Any]) -> None:
    """Run a 4-turn synthetic conversation for one specialist.

    Turn shape:
      1. Agent (us): opening line per category
      2. Counterparty: opener question
      3. Agent: answer with spec details
      4. Counterparty: confirm with reference number
      (optional) 5. Agent: final bid line

    Each agent turn goes through real PAVO routing. Each counterparty turn is
    pre-templated but emitted to the dashboard so the wall feels alive.
    """
    event = state.events.get(event_id)
    if event is None:
        return

    ctx = event.specialist_calls.get(persona.agent_id)
    if ctx is None:
        return

    cat = persona.category
    if cat not in AGENT_OPENERS:
        log.warning("synthetic mode: no template for category %s", cat)
        return

    # Transition: dispatched → calling → in-progress
    for new_state in ("calling", "in-progress"):
        ctx.state = new_state
        await ws_broker.broadcast({
            "type": "agent_state", "event_id": event_id,
            "agent_id": persona.agent_id, "state": new_state,
            "ts": time.time(),
        })
        await asyncio.sleep(0.4)

    counterparty_lines = [
        COUNTERPARTY_OPENERS[cat],
        *COUNTERPARTY_TURN_TEMPLATES[cat],
    ]

    # Pace the 4 agent turns + 4 counterparty turns across roughly 35 seconds.
    for turn_idx in range(4):
        # Counterparty turn (template fill).
        counterparty_text = _format(counterparty_lines[turn_idx], spec)
        ctx.turn_count += 1
        ctx.transcript.append({"role": "counterparty", "text": counterparty_text, "ts": time.time()})
        await ws_broker.broadcast({
            "type": "transcript_turn", "event_id": event_id, "agent_id": persona.agent_id,
            "turn": ctx.turn_count, "role": "counterparty", "text": counterparty_text, "ts": time.time(),
        })
        await asyncio.sleep(1.2 + 0.3 * turn_idx)

        # Agent turn (real PAVO call).
        if turn_idx == 0:
            user_input = AGENT_OPENERS[cat]
            agent_msg = _format(user_input, spec)
            # Skip PAVO for the opener — it's pre-scripted to keep latency tight.
            tier = "gemma-local"
            cost_cents = 0.0005
            decision_reason = "synthetic opener (pre-scripted)"
        else:
            messages = [
                {"role": "system", "content": persona.system_prompt},
                {"role": "user", "content": counterparty_text},
            ]
            reply = await pavo_chat(messages, role_hint=persona.role_hint, max_tokens=120)
            agent_msg = reply.content
            tier = reply.tier
            cost_cents = reply.cost_cents
            decision_reason = reply.decision_reason

            # Update cost ticker on each real PAVO call.
            event.pavo_cents_total += cost_cents
            event.baseline_cents_total += cost_cents * 4  # rough cloud baseline ratio per paper
            await ws_broker.broadcast({
                "type": "routing_decision", "event_id": event_id, "agent_id": persona.agent_id,
                "turn": ctx.turn_count + 1, "tier": tier, "reason": decision_reason,
                "complexity": 0.0, "ts": time.time(),
            })
            await ws_broker.broadcast({
                "type": "cost_update", "event_id": event_id,
                "pavo_cents": event.pavo_cents_total, "baseline_cents": event.baseline_cents_total,
                "ts": time.time(),
            })

        ctx.turn_count += 1
        ctx.transcript.append({"role": "agent", "text": agent_msg, "pavo_tier": tier, "ts": time.time()})
        await ws_broker.broadcast({
            "type": "transcript_turn", "event_id": event_id, "agent_id": persona.agent_id,
            "turn": ctx.turn_count, "role": "agent", "text": agent_msg,
            "pavo_tier": tier, "ts": time.time(),
        })
        await asyncio.sleep(0.8 + 0.2 * turn_idx)

    # Final state: closed
    ctx.state = "closed"
    ctx.closed_at = time.time()
    ctx.bid = {"synthetic": True, "category": cat}
    await ws_broker.broadcast({
        "type": "agent_state", "event_id": event_id, "agent_id": persona.agent_id,
        "state": "closed", "ts": time.time(),
    })


async def run_synthetic_fan_out(event_id: str, spec: dict[str, Any], specialists: list[Persona]) -> None:
    """Run synthetic conversations for all specialists in parallel."""
    # Default missing spec fields so templates render.
    spec_filled = {
        "user_name": "the customer",
        "origin_address": spec.get("origin_address", "the SF address"),
        "destination_address": spec.get("destination_address", "the Austin address"),
        "move_date": spec.get("move_date", "May 31"),
        **spec,
    }
    await asyncio.gather(*[run_synthetic_specialist(p, event_id, spec_filled) for p in specialists])

    # Event complete: trigger the same post-completion sponsor fan-out as the real flow.
    # (Imported here to avoid circular import at module load.)
    from .main import _fire_event_complete_sponsors
    await _fire_event_complete_sponsors(event_id)
