"""Synthetic-demo mode — runs realistic 4-turn fake conversations per specialist
via PAVO directly, without AgentPhone.

Use cases:
  1. Rehearsal: run the full demo flow without needing AgentPhone API keys.
  2. Backup video: record a clean 90-second demo for the worst-case scenario
     where AgentPhone fails on stage.
  3. Pre-stage testing: verify the dashboard + PAVO + cost ticker without
     waiting for real outbound calls to connect.

Architecture:
  - Each specialist runs a 4-turn conversation in-process (no AgentPhone, no webhook)
  - Both sides of the conversation are generated by PAVO via separate role_hints
  - Real PAVO routing decisions fire (the routing layer is genuinely exercised)
  - Real cost is accumulated (gemma-local turns ~0.005c each; gemini-flash 18%; opus 2%)
  - All WebSocket events flow normally to the dashboard

The synthetic counterparty turns use a different role_hint ("counterparty-{category}")
so PAVO can still classify them appropriately. For the demo, this is real PAVO
routing — only the AgentPhone leg is skipped.
"""
from __future__ import annotations

import asyncio
import logging
import time
from typing import Any

from .pavo_client import pavo_chat
from .personas import Persona
from .state import state
from .ws import ws_broker


log = logging.getLogger(__name__)


# Per-category prompt scaffolding to make synthetic counterparty replies feel real.
COUNTERPARTY_OPENERS = {
    "utility-electric-gas": "PG&E customer service, this is Diana, how can I help you?",
    "utility-internet-sf": "Thanks for calling Comcast retention, this is Marcus.",
    "insurance-auto": "Geico, this is Patricia, may I have your policy number?",
    "postal": "USPS COA form loaded.",
    "utility-internet-austin": "Spectrum new service, this is Ryan, how can I help?",
    "mover": "Atlas Moving and Storage, this is Tony. How can I help?",
}


COUNTERPARTY_TURN_TEMPLATES = {
    "utility-electric-gas": [
        "What's the account holder's name and service address?",
        "Got it. We can schedule disconnect for {move_date}. Will there be anyone at the property for the meter read?",
        "Confirmed. Disconnect scheduled for {move_date}, confirmation 8472341. Final bill will arrive within 4 weeks.",
    ],
    "utility-internet-sf": [
        "I see the account. Why are we losing you? Anything we can do?",
        "I understand. Effective date {move_date}. There's an early-termination fee but we'll waive it for out-of-area moves. Final bill is in 2 cycles.",
        "Cancellation confirmation 41872, final bill {move_date_plus_45}. Please return your modem within 14 days.",
    ],
    "insurance-auto": [
        "Got the policy. Old address San Francisco, new address Austin Texas. New rate is $142 a month, down from your $186. Effective {move_date}.",
        "Confirmation reference TX-948-2A. New policy card mails out tomorrow.",
        "Anything else?",
    ],
    "postal": [
        "Filling: old SF address, new Austin address, move date {move_date}, family.",
        "Step 2: identity verification charge $1.10 against the card on file. Confirming.",
        "Submission complete. USPS confirmation 4081-3293-7762-4419. COA effective {move_date}.",
    ],
    "utility-internet-austin": [
        "Welcome. Service address please?",
        "Coverage confirmed. Spectrum Internet Ultra 500 megabit, install on {move_date}, technician between 8 AM and noon. Install fee $50 — waiving as new account.",
        "Work order WO2847391024. We'll text you when the tech is 30 minutes out.",
    ],
    "mover": [
        "2-bedroom San Francisco to Austin, May 31 — let me work up a quote. About 5,000 pounds, no piano, no safe?",
        "OK. Out the door $1,840 includes packing, fuel, basic insurance. Deposit $500, balance due on delivery. Truck confirmed for May 31.",
        "I can hold the slot for 24 hours. After that I can't promise.",
    ],
}

AGENT_OPENERS = {
    "utility-electric-gas": "Hi, calling on behalf of {user_name} to schedule a service disconnect at {origin_address} on {move_date}.",
    "utility-internet-sf": "Hi, calling to cancel Comcast service at {origin_address}, effective {move_date}.",
    "insurance-auto": "Hello, calling to update the policy mailing and garage address. Old: {origin_address}. New: {destination_address}. Effective {move_date}.",
    "postal": "Initiating COA: old {origin_address}, new {destination_address}, move date {move_date}.",
    "utility-internet-austin": "Hi, scheduling new internet install at {destination_address}, target install {move_date}.",
    "mover": "Calling for an out-the-door quote: 2BR move from {origin_address} to {destination_address}, target {move_date}.",
    "bank": "Calling to update mailing address on all linked accounts: old {origin_address}, new {destination_address}.",
    "school": "Hi, AISD transfer office? Initiating enrollment for a student moving from SFUSD to Austin effective {move_date}.",
    "medical-records": "Hi, requesting medical records transfer for our patient — moving to Austin, effective {move_date}. HIPAA release on file.",
    "vet": "Hi, calling about my pet's records — we're moving to Austin {move_date}. Need them transferred to a new vet.",
    "gym": "Calling to cancel membership effective {move_date} — moving out of state.",
    "pharmacy": "Hi CVS — transferring active prescriptions to CVS Austin, target pickup {move_date}.",
    "dmv": "Updating CA DL address from {origin_address} to {destination_address} via the MyDMV portal.",
    "voter": "Updating CA voter registration from {origin_address} to {destination_address}.",
    "subscriptions": "Sweeping subscription portals — updating mailing address from {origin_address} to {destination_address}.",
}


# Counterparty openers for the new agents — voice that picks up.
GENERIC_COUNTERPARTY_OPENERS = {
    "bank": "Wells Fargo customer service, this is Janet, how can I help?",
    "school": "Austin ISD transfer office, this is Tara — what grade is the student?",
    "medical-records": "One Medical records team, this is Devon. What's the patient's date of birth?",
    "vet": "SF Pet Clinic, this is Carla. Pet's name?",
    "gym": "Equinox member services, this is Anya. Can I get your member ID?",
    "pharmacy": "CVS Pharmacy, this is Marcus. Prescription transfer?",
    "dmv": "MyDMV portal opened. Step 1 of 4: confirm current DL number.",
    "voter": "registertovote.ca.gov loaded. Step 1: confirm name + DOB.",
    "subscriptions": "Costco account portal — logged in.",
}

# Generic 3-turn counterparty templates for the new agents (good-enough demo dialogue).
GENERIC_COUNTERPARTY_TEMPLATES = {
    "bank": [
        "I see the account. To verify — last 4 of SSN?",
        "Verified. Mailing address on all three accounts updated to {destination_address}, effective {move_date}. Confirmation WF-29847.",
        "Anything else today?",
    ],
    "school": [
        "Got it. We'll need immunization records and the prior school transcript. Records request already faxed?",
        "Perfect. Enrollment packet will arrive at {destination_address} within 5 business days. Reference AISD-{move_date}-118.",
        "Welcome to AISD. Is there anything else?",
    ],
    "medical-records": [
        "I see the HIPAA release. Destination provider name and fax?",
        "Records request in queue. ETA 7-10 business days. Reference OM-RT-3392.",
        "Anything else for your patient?",
    ],
    "vet": [
        "Sure. We'll fax full records — vaccines, surgical history, current meds. Destination clinic?",
        "Done. Records sent. Reference VET-MV-1208.",
        "Safe move.",
    ],
    "gym": [
        "Cancellation is final after 30 days — that's the policy. Want to suspend instead?",
        "OK, cancellation effective {move_date}. Confirmation EQX-CN-882. Final pro-rated bill in 5 business days.",
        "Sorry to see you go.",
    ],
    "pharmacy": [
        "Active scripts: lisinopril 10mg, atorvastatin 20mg, citalopram 20mg. Transfer to CVS Austin store 8842?",
        "Transfer initiated. Pickup ready by {move_date} at the destination store. Reference CVS-TX-4471.",
        "Anything else?",
    ],
    "dmv": [
        "Step 2: confirm date of birth. Step 3: enter new residence address.",
        "Step 4: submit for review. CA-DMV-CN-7741 issued. New DL card mails within 10 business days.",
        "Address change complete.",
    ],
    "voter": [
        "Step 2: select your party preference (skip if no change).",
        "Step 3: submit. Confirmation VR-{move_date}-228. Sample ballot mails 30 days before next election.",
        "Registration updated.",
    ],
    "subscriptions": [
        "Logged in. Updating: Amazon, Netflix, NYTimes, Audible.",
        "All 4 portals updated to {destination_address}. Per-portal confirmations sent to your email.",
        "Digest queued.",
    ],
}

# Merge generics into the main templates dict.
COUNTERPARTY_OPENERS.update(GENERIC_COUNTERPARTY_OPENERS)
COUNTERPARTY_TURN_TEMPLATES.update(GENERIC_COUNTERPARTY_TEMPLATES)


def _format(template: str, spec: dict[str, Any]) -> str:
    """Naive format helper that swallows missing keys."""
    try:
        return template.format(**spec, move_date_plus_45="early July")
    except KeyError as e:
        log.warning("synthetic template missing key %s; substituting placeholder", e)
        return template.format_map({**spec, "move_date_plus_45": "early July", str(e).strip("'"): "<unknown>"})


async def run_synthetic_specialist(persona: Persona, event_id: str, spec: dict[str, Any]) -> None:
    """Run a 4-turn synthetic conversation for one specialist.

    Turn shape:
      1. Agent (us): opening line per category
      2. Counterparty: opener question
      3. Agent: answer with spec details
      4. Counterparty: confirm with reference number
      (optional) 5. Agent: final bid line

    Each agent turn goes through real PAVO routing. Each counterparty turn is
    pre-templated but emitted to the dashboard so the wall feels alive.
    """
    event = state.events.get(event_id)
    if event is None:
        return

    ctx = event.specialist_calls.get(persona.agent_id)
    if ctx is None:
        return

    cat = persona.category
    if cat not in AGENT_OPENERS:
        log.warning("synthetic mode: no template for category %s", cat)
        return

    # Transition: dispatched → calling → in-progress
    for new_state in ("calling", "in-progress"):
        ctx.state = new_state
        await ws_broker.broadcast({
            "type": "agent_state", "event_id": event_id,
            "agent_id": persona.agent_id, "state": new_state,
            "ts": time.time(),
        })
        await asyncio.sleep(0.4)

    counterparty_lines = [
        COUNTERPARTY_OPENERS[cat],
        *COUNTERPARTY_TURN_TEMPLATES[cat],
    ]

    # Pace the 4 agent turns + 4 counterparty turns across roughly 35 seconds.
    for turn_idx in range(4):
        # Counterparty turn (template fill).
        counterparty_text = _format(counterparty_lines[turn_idx], spec)
        ctx.turn_count += 1
        ctx.transcript.append({"role": "counterparty", "text": counterparty_text, "ts": time.time()})
        await ws_broker.broadcast({
            "type": "transcript_turn", "event_id": event_id, "agent_id": persona.agent_id,
            "turn": ctx.turn_count, "role": "counterparty", "text": counterparty_text, "ts": time.time(),
        })
        await asyncio.sleep(1.2 + 0.3 * turn_idx)

        # Agent turn (real PAVO call).
        if turn_idx == 0:
            user_input = AGENT_OPENERS[cat]
            agent_msg = _format(user_input, spec)
            # Skip PAVO for the opener — it's pre-scripted to keep latency tight.
            tier = "gemma-local"
            cost_cents = 0.0005
            decision_reason = "synthetic opener (pre-scripted)"
        else:
            messages = [
                {"role": "system", "content": persona.system_prompt},
                {"role": "user", "content": counterparty_text},
            ]
            reply = await pavo_chat(messages, role_hint=persona.role_hint, max_tokens=120)
            agent_msg = reply.content
            tier = reply.tier
            cost_cents = reply.cost_cents
            decision_reason = reply.decision_reason

            # Update cost ticker on each real PAVO call.
            event.pavo_cents_total += cost_cents
            await ws_broker.broadcast({
                "type": "routing_decision", "event_id": event_id, "agent_id": persona.agent_id,
                "turn": ctx.turn_count + 1, "tier": tier, "reason": decision_reason,
                "complexity": 0.0, "ts": time.time(),
            })
            await ws_broker.broadcast({
                "type": "cost_update", "event_id": event_id,
                "pavo_cents": event.pavo_cents_total, "baseline_cents": event.baseline_cents_total,
                "ts": time.time(),
            })

        ctx.turn_count += 1
        ctx.transcript.append({"role": "agent", "text": agent_msg, "pavo_tier": tier, "ts": time.time()})
        await ws_broker.broadcast({
            "type": "transcript_turn", "event_id": event_id, "agent_id": persona.agent_id,
            "turn": ctx.turn_count, "role": "agent", "text": agent_msg,
            "pavo_tier": tier, "ts": time.time(),
        })
        await asyncio.sleep(0.8 + 0.2 * turn_idx)

    # Final state: closed
    ctx.state = "closed"
    ctx.closed_at = time.time()
    ctx.bid = {"synthetic": True, "category": cat}
    await ws_broker.broadcast({
        "type": "agent_state", "event_id": event_id, "agent_id": persona.agent_id,
        "state": "closed", "ts": time.time(),
    })

    # Fire the per-agent REAL artifacts: AgentMail email + Supermemory persist.
    # Each agent now produces its own verifiable artifact, not just the bundled PDF.
    from .integrations.per_agent_artifacts import fire_per_agent_artifacts
    homeowner_email = (
        spec.get("homeowner_email")
        or "vnarasingamoorthy@gmail.com"
    )
    # Extract a short outcome line — last agent turn or a fallback.
    last_agent = next((t for t in reversed(ctx.transcript) if t.get("role") == "agent"), None)
    outcome_text = ""
    if last_agent:
        text = last_agent.get("text", "")
        import re
        m = re.search(r"Bid:\s*(.*?)(?:\.|$)", text)
        outcome_text = (m.group(1) if m else text)[:140].strip()
    asyncio.create_task(
        fire_per_agent_artifacts(
            event_id=event_id,
            agent_id=persona.agent_id,
            spec=spec,
            outcome_text=outcome_text,
            homeowner_email=homeowner_email,
        )
    )


async def run_synthetic_fan_out(event_id: str, spec: dict[str, Any], specialists: list[Persona]) -> None:
    """Run synthetic conversations for all specialists in parallel."""
    # Default missing spec fields so templates render.
    spec_filled = {
        "user_name": "the customer",
        "origin_address": spec.get("origin_address", "the SF address"),
        "destination_address": spec.get("destination_address", "the Austin address"),
        "move_date": spec.get("move_date", "May 31"),
        **spec,
    }
    await asyncio.gather(*[run_synthetic_specialist(p, event_id, spec_filled) for p in specialists])
